DotNetCoreApps/WebApplication1/Patl.WebApp/Controllers/ApplicationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.Extensions.Configuration;
using Patl.WebApp.Services;
using Patl.WebApp.ViewModels;

namespace Patl.WebApp.Views
{
    public class ApplicationController : Controller
    {
        private IMailService _mailService;
        private IConfigurationRoot _config;

        public ApplicationController(IMailService mailService, IConfigurationRoot config)
        {
            _mailService = mailService;
            _config = config;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Info()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (model.Email.Contains("aol.com"))
            {
                ModelState.AddModelError("", "We don't support AOL addresses");
            }

            string emailaddress = _config["MailSettings:ToAddress"];

            if (ModelState.IsValid)
            {
                _mailService.SendMail(_config["MailSettings:ToAddress"], model.Email, "From TheWorld", model.Message);
                ModelState.Clear();
                ViewBag.UserMessage = "Message Sent";
            }
            return View();
        }

        public IActionResult Error()
        {
            throw new InvalidOperationException("raz dwa trzy babajaga patrzy");
        }
    }
}

DotNetCoreApps/WebApplication1/Patl.WebApp/Views/Shared/TradeOverviewSummary.cshtml
@model Trade
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.PriceOpen.ToString("c")</h3>
            <h3>
                <a>@Model.Name</a>
            </h3>
            <p>@Model.Description</p>
        </div>
    </div>
</div>

DotNetCoreApps/WebApplication1/Patl.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <title> Price Action Log Book </title>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" alt="Bethany's Pie Shop'" src="~/Images/bethanylogo.png" />
                </p>
                <p>
                    <a asp-controller="Application" asp-action="Error">link00 1</a>
                    <a asp-controller="Application" asp-action="Contact">Contact</a>
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>